# ============================================================
# application.conf — Cortex 3.1.7
# Chemin dans le conteneur : /etc/cortex/application.conf
# ============================================================

# Secret key
play.http.secret.key = "CHANGE_ME_RANDOM_SECRET_KEY"

# Elasticsearch
search {
  index = cortex
  uri = "http://elasticsearch:9200"
}

# Docker runner
docker {
  pullImage = false
}

# Analyseurs — fichier local (évite re-téléchargement depuis internet)
analyzer {
  urls = [
    "file:///etc/cortex/analyzers.json"
  ]
}

# Responders
responder {
  urls = [
    "https://download.thehive-project.org/responders.json"
  ]
}
